### ISSUE TITLE
Enum naming convention

### ISSUE THREAD

**Issue by robertnorenberg** [ForeignSasquatch/hxRaylib#20]
So I've noticed that there are two conventions as for the enums:
- repeating the prefix: e.g. `MOUSE_CURSOR_DEFAULT -> Raylib.MouseCursor.MOUSE_CURSOR_DEFAULT`
- not repeating the prefix: e.g.`MOUSE_BUTTON_LEFT -> Raylib.MouseButton.LEFT`

The shorter seam nicer but either is better than both imo.

Not sure if worth the hustle though - let me know; I can prepare a pr for that.

**Comment by ForeignSasquatch** [comment]
Originally I used the first one but they must be the second one. Thank you for the prs 😄
